# This is a basic workflow to help you get started with Actions

name: generate github history snake animation
on:
  schedule:
    - cron : 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository
      - uses: actions/checkout@v2
      
      # Generates the snake animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: "AbdelkrimElAyachi"
          # The size of the generated GIF
          gif_out_path: dist/github-contribution-grid-snake.gif
          # Path of the generated SVG file
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Pushes the changes to your repository
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.HISTORY_SNAKE_TOKEN }}
